# Generated by Django 6.0.2 on 2026-02-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_customuser_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.CharField()),
                ('genres', models.CharField(max_length=100)),
                ('keywords', models.CharField()),
                ('cast', models.CharField()),
                ('crew', models.CharField()),
                ('release_date', models.DateField()),
                ('popularity', models.FloatField()),
                ('runtime', models.IntegerField()),
                ('spoken_languages', models.CharField()),
                ('tags', models.CharField()),
            ],
        ),
    ]
