# Generated by Django 6.0.2 on 2026-02-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_movie_csv_id_alter_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='csv_id',
            field=models.IntegerField(),
        ),
    ]
